In [1]:
import numpy as np
import pandas as pd

In [2]:
test_data = pd.read_csv("Dataset/test.csv")
train_data = pd.read_csv("Dataset/train.csv")
building_ownership = pd.read_csv("Dataset/Building_Ownership_Use.csv")
building_structure = pd.read_csv("Dataset/Building_Structure.csv")

In [4]:
test_data.head()

,area_assesed,building_id,district_id,has_geotechnical_risk,has_geotechnical_risk_fault_crack,has_geotechnical_risk_flood,has_geotechnical_risk_land_settlement,has_geotechnical_risk_landslide,has_geotechnical_risk_liquefaction,has_geotechnical_risk_other,has_geotechnical_risk_rock_fall,has_repair_started,vdcmun_id
0,Both,a3380c4f75,7,0.0,0,0,0,0,0,0,0,1.0,701
1,Both,a338a4e653,7,0.0,0,0,0,0,0,0,0,1.0,701
2,Building removed,a338a4e6b7,7,0.0,0,0,0,0,0,0,0,1.0,701
3,Both,a33a6eaa3a,7,0.0,0,0,0,0,0,0,0,1.0,701
4,Building removed,a33b073ff6,7,0.0,0,0,0,0,0,0,0,1.0,701

In [5]:
print(train_data.shape)
print(building_ownership.shape)
print(building_structure.shape)

(631761, 14)
(1052948, 17)
(1052948, 29)

In [6]:
train_data.head()

,area_assesed,building_id,damage_grade,district_id,has_geotechnical_risk,has_geotechnical_risk_fault_crack,has_geotechnical_risk_flood,has_geotechnical_risk_land_settlement,has_geotechnical_risk_landslide,has_geotechnical_risk_liquefaction,has_geotechnical_risk_other,has_geotechnical_risk_rock_fall,has_repair_started,vdcmun_id
0,Both,24385bfd2a2,Grade 4,24,0.0,0,0,0,0,0,0,0,0.0,2489
1,Both,405d1bbebbf,Grade 2,44,0.0,0,0,0,0,0,0,0,1.0,4423
2,Both,351d9bc71f6,Grade 1,36,0.0,0,0,0,0,0,0,0,0.0,3650
3,Building removed,2be3a971166,Grade 5,30,0.0,0,0,0,0,0,0,0,0.0,3016
4,Both,34c7d073ea6,Grade 3,36,0.0,0,0,0,0,0,0,0,0.0,3627

In [42]:
#del building_ownership['district_id']
building_ownership.head()

,building_id,ward_id,legal_ownership_status,count_families,has_secondary_use,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,a3380c4f75,70102,2,1.0,0.0,0,0,0,0,0,0,0,0,0,0
1,a3380c4fd9,70102,2,1.0,0.0,0,0,0,0,0,0,0,0,0,0
2,a3380c503e,70102,2,1.0,0.0,0,0,0,0,0,0,0,0,0,0
3,a338a4e5f2,70103,2,1.0,0.0,0,0,0,0,0,0,0,0,0,0
4,a338a4e653,70103,2,1.0,0.0,0,0,0,0,0,0,0,0,0,0

In [44]:
del building_ownership['vdcmun_id']

In [46]:
del building_ownership['district_id']

In [40]:
building_ownership.head()

,building_id,ward_id,legal_ownership_status,count_families,has_secondary_use,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,a3380c4f75,70102,2,1.0,0.0,0,0,0,0,0,0,0,0,0,0
1,a3380c4fd9,70102,2,1.0,0.0,0,0,0,0,0,0,0,0,0,0
2,a3380c503e,70102,2,1.0,0.0,0,0,0,0,0,0,0,0,0,0
3,a338a4e5f2,70103,2,1.0,0.0,0,0,0,0,0,0,0,0,0,0
4,a338a4e653,70103,2,1.0,0.0,0,0,0,0,0,0,0,0,0,0

In [47]:
building_structure.head()

,building_id,count_floors_pre_eq,count_floors_post_eq,age_building,plinth_area_sq_ft,height_ft_pre_eq,height_ft_post_eq,land_surface_condition,foundation_type,roof_type,...,has_superstructure_stone_flag,has_superstructure_cement_mortar_stone,has_superstructure_mud_mortar_brick,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other,condition_post_eq
0,a3380c4f75,1,1,28,454,9,9,1,2,1,...,0,0,0,0,1,1,0,0,1,2
1,a3380c4fd9,1,1,32,324,9,9,1,2,1,...,0,0,0,0,1,1,0,0,1,2
2,a3380c503e,2,2,34,456,18,18,1,2,1,...,0,0,0,0,1,1,0,0,1,2
3,a338a4e5f2,2,2,20,452,18,18,1,2,1,...,0,0,0,0,1,1,0,0,1,2
4,a338a4e653,1,0,25,542,9,0,1,2,1,...,0,0,0,0,1,1,0,0,1,5

In [10]:
del building_structure['vdcmun_id', '']

In [11]:
del building_structure['ward_id']

In [12]:
del building_structure['district_id']

In [48]:
building_structure.head()

,building_id,count_floors_pre_eq,count_floors_post_eq,age_building,plinth_area_sq_ft,height_ft_pre_eq,height_ft_post_eq,land_surface_condition,foundation_type,roof_type,...,has_superstructure_stone_flag,has_superstructure_cement_mortar_stone,has_superstructure_mud_mortar_brick,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other,condition_post_eq
0,a3380c4f75,1,1,28,454,9,9,1,2,1,...,0,0,0,0,1,1,0,0,1,2
1,a3380c4fd9,1,1,32,324,9,9,1,2,1,...,0,0,0,0,1,1,0,0,1,2
2,a3380c503e,2,2,34,456,18,18,1,2,1,...,0,0,0,0,1,1,0,0,1,2
3,a338a4e5f2,2,2,20,452,18,18,1,2,1,...,0,0,0,0,1,1,0,0,1,2
4,a338a4e653,1,0,25,542,9,0,1,2,1,...,0,0,0,0,1,1,0,0,1,5

In [49]:
from sklearn.preprocessing import LabelEncoder

In [50]:
train_data.area_assesed = LabelEncoder().fit_transform(train_data.area_assesed)
train_data.head()

,area_assesed,building_id,damage_grade,district_id,has_geotechnical_risk,has_geotechnical_risk_fault_crack,has_geotechnical_risk_flood,has_geotechnical_risk_land_settlement,has_geotechnical_risk_landslide,has_geotechnical_risk_liquefaction,has_geotechnical_risk_other,has_geotechnical_risk_rock_fall,has_repair_started,vdcmun_id
0,0,24385bfd2a2,Grade 4,24,0.0,0,0,0,0,0,0,0,0.0,2489
1,0,405d1bbebbf,Grade 2,44,0.0,0,0,0,0,0,0,0,1.0,4423
2,0,351d9bc71f6,Grade 1,36,0.0,0,0,0,0,0,0,0,0.0,3650
3,1,2be3a971166,Grade 5,30,0.0,0,0,0,0,0,0,0,0.0,3016
4,0,34c7d073ea6,Grade 3,36,0.0,0,0,0,0,0,0,0,0.0,3627

In [51]:
building_ownership.legal_ownership_status = LabelEncoder().fit_transform(building_ownership.legal_ownership_status)
building_ownership.head()

,building_id,ward_id,legal_ownership_status,count_families,has_secondary_use,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
0,a3380c4f75,70102,2,1.0,0.0,0,0,0,0,0,0,0,0,0,0
1,a3380c4fd9,70102,2,1.0,0.0,0,0,0,0,0,0,0,0,0,0
2,a3380c503e,70102,2,1.0,0.0,0,0,0,0,0,0,0,0,0,0
3,a338a4e5f2,70103,2,1.0,0.0,0,0,0,0,0,0,0,0,0,0
4,a338a4e653,70103,2,1.0,0.0,0,0,0,0,0,0,0,0,0,0

In [52]:
building_structure.land_surface_condition =LabelEncoder().fit_transform(building_structure.land_surface_condition)

In [53]:
building_structure.foundation_type=LabelEncoder().fit_transform(building_structure.foundation_type)

In [54]:
building_structure.roof_type=LabelEncoder().fit_transform(building_structure.roof_type)

In [55]:
building_structure.condition_post_eq=LabelEncoder().fit_transform(building_structure.condition_post_eq)

In [56]:
building_structure.ground_floor_type=LabelEncoder().fit_transform(building_structure.ground_floor_type)
building_structure.ground_floor_type.dtype

dtype('int64')

In [57]:
building_structure.other_floor_type=LabelEncoder().fit_transform(building_structure.other_floor_type)

In [58]:
building_structure['position']= building_structure['position'].astype('str')

In [59]:
building_structure.position.dtype

dtype('O')

In [60]:
building_structure.position = LabelEncoder().fit_transform(building_structure.position)

In [61]:
building_structure['plan_configuration']=building_structure['plan_configuration'].astype('str')

In [62]:
building_structure.plan_configuration = LabelEncoder().fit_transform(building_structure.plan_configuration)

In [63]:
building_structure.plan_configuration.describe()

count    1.052948e+06
mean     6.976813e+00
std      4.281706e-01
min      0.000000e+00
25%      7.000000e+00
50%      7.000000e+00
75%      7.000000e+00
max      1.000000e+01
Name: plan_configuration, dtype: float64

In [64]:
print(train_data.shape)
print(building_ownership.shape)
print(building_structure.shape)

(631761, 14)
(1052948, 15)
(1052948, 26)

In [65]:
merge_train1=pd.merge(train_data,building_ownership, on='building_id',how='outer')

In [66]:
merge_train1=pd.merge(train_data,building_ownership, on='building_id',how='outer')

In [32]:
merge_train1=pd.merge(train_data,building_ownership, on='building_id',how='outer')

In [67]:
merge_train1.shape

(1052948, 28)

In [68]:

merge_train2=pd.merge(merge_train1,building_structure, on='building_id',how='outer')

In [69]:
merge_train2.shape

(1052948, 53)

In [70]:
merge_train2.head()

,area_assesed,building_id,damage_grade,district_id,has_geotechnical_risk,has_geotechnical_risk_fault_crack,has_geotechnical_risk_flood,has_geotechnical_risk_land_settlement,has_geotechnical_risk_landslide,has_geotechnical_risk_liquefaction,...,has_superstructure_stone_flag,has_superstructure_cement_mortar_stone,has_superstructure_mud_mortar_brick,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other,condition_post_eq
0,0.0,24385bfd2a2,Grade 4,24.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
1,0.0,405d1bbebbf,Grade 2,44.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,0,0,0,0,0,2
2,0.0,351d9bc71f6,Grade 1,36.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,1,0,7
3,1.0,2be3a971166,Grade 5,30.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,4
4,0.0,34c7d073ea6,Grade 3,36.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,6

In [37]:
merge_train2.shape

(1052948, 54)

In [38]:
merge_train2.shape

(1052948, 54)

In [71]:
merge_train2.dropna(inplace=True)

In [72]:
merge_train2.shape

(598343, 53)

In [73]:
merge_train2.isna().sum()

area_assesed                              0
building_id                               0
damage_grade                              0
district_id                               0
has_geotechnical_risk                     0
has_geotechnical_risk_fault_crack         0
has_geotechnical_risk_flood               0
has_geotechnical_risk_land_settlement     0
has_geotechnical_risk_landslide           0
has_geotechnical_risk_liquefaction        0
has_geotechnical_risk_other               0
has_geotechnical_risk_rock_fall           0
has_repair_started                        0
vdcmun_id                                 0
ward_id                                   0
legal_ownership_status                    0
count_families                            0
has_secondary_use                         0
has_secondary_use_agriculture             0
has_secondary_use_hotel                   0
has_secondary_use_rental                  0
has_secondary_use_institution             0
has_secondary_use_school                  0
has_secondary_use_industry                0
has_secondary_use_health_post             0
has_secondary_use_gov_office              0
has_secondary_use_use_police              0
has_secondary_use_other                   0
count_floors_pre_eq                       0
count_floors_post_eq                      0
age_building                              0
plinth_area_sq_ft                         0
height_ft_pre_eq                          0
height_ft_post_eq                         0
land_surface_condition                    0
foundation_type                           0
roof_type                                 0
ground_floor_type                         0
other_floor_type                          0
position                                  0
plan_configuration                        0
has_superstructure_adobe_mud              0
has_superstructure_mud_mortar_stone       0
has_superstructure_stone_flag             0
has_superstructure_cement_mortar_stone    0
has_superstructure_mud_mortar_brick       0
has_superstructure_cement_mortar_brick    0
has_superstructure_timber                 0
has_superstructure_bamboo                 0
has_superstructure_rc_non_engineered      0
has_superstructure_rc_engineered          0
has_superstructure_other                  0
condition_post_eq                         0
dtype: int64

In [74]:
y=merge_train2.damage_grade

In [75]:
del merge_train2['damage_grade']

In [76]:
del merge_train2['building_id']

In [77]:
X = merge_train2

In [79]:
from sklearn.cross_validation import train_test_split

In [80]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.10, random_state=42)

In [81]:
from sklearn.tree import DecisionTreeClassifier

In [82]:
clf = DecisionTreeClassifier()

In [83]:
print(len(X_train))
print(len(y_train))

538508
538508

In [84]:
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [85]:
from sklearn.metrics import classification_report

In [86]:
print(classification_report(clf.predict(X_test), y_test))

             precision    recall  f1-score   support

    Grade 1       0.75      0.73      0.74      2916
    Grade 2       0.49      0.49      0.49      8542
    Grade 3       0.48      0.46      0.47     12510
    Grade 4       0.64      0.66      0.65     14785
    Grade 5       0.96      0.96      0.96     21082

avg / total       0.70      0.70      0.70     59835

In [127]:
from sklearn.ensemble import RandomForestClassifier

In [128]:
RandomForestClassifier

sklearn.ensemble.forest.RandomForestClassifier

In [129]:
forest_clf = RandomForestClassifier(n_estimators=20, n_jobs=-1)

In [130]:
forest_clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=-1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [131]:
pred = forest_clf.predict(X_test)

In [34]:
print(classification_report(pred, y_test))

             precision    recall  f1-score   support

    Grade 1       0.27      0.48      0.34      3971
    Grade 2       0.47      0.46      0.46     21705
    Grade 3       0.42      0.49      0.45     26110
    Grade 4       0.66      0.55      0.60     45593
    Grade 5       0.89      0.89      0.89     52207

avg / total       0.66      0.64      0.65    149586

In [87]:
test = test_data.copy()

In [88]:
test.shape

(421175, 13)

In [89]:
building_ownership.isna().sum()

building_id                       0
ward_id                           0
legal_ownership_status            0
count_families                    2
has_secondary_use                10
has_secondary_use_agriculture     0
has_secondary_use_hotel           0
has_secondary_use_rental          0
has_secondary_use_institution     0
has_secondary_use_school          0
has_secondary_use_industry        0
has_secondary_use_health_post     0
has_secondary_use_gov_office      0
has_secondary_use_use_police      0
has_secondary_use_other           0
dtype: int64

In [90]:

building_ownership['count_families'].fillna(building_ownership['count_families'].mode()[0], inplace=True)

In [91]:

building_ownership['has_secondary_use'].fillna(building_ownership['has_secondary_use'].mode()[0], inplace=True)

In [92]:
building_structure.isna().sum()
building_structure.shape

(1052948, 26)

In [93]:
test.isna().sum()

area_assesed                                 0
building_id                                  0
district_id                                  0
has_geotechnical_risk                        0
has_geotechnical_risk_fault_crack            0
has_geotechnical_risk_flood                  0
has_geotechnical_risk_land_settlement        0
has_geotechnical_risk_landslide              0
has_geotechnical_risk_liquefaction           0
has_geotechnical_risk_other                  0
has_geotechnical_risk_rock_fall              0
has_repair_started                       21922
vdcmun_id                                    0
dtype: int64

In [94]:
test['has_repair_started'].mode()[0]

0.0

In [95]:

test['has_repair_started'].fillna(0, inplace=True)

In [96]:
test.shape

(421175, 13)

In [97]:
merge_test1=pd.merge(test,building_ownership,on='building_id',how='outer')

In [98]:
merge_test1.shape

(1052948, 27)

In [99]:
merge_test2=pd.merge(merge_test1,building_structure,on='building_id',how='outer')

In [100]:
merge_test2.shape

(1052948, 52)

In [101]:
merge_test2.isna().sum()

area_assesed                              631773
building_id                                    0
district_id                               631773
has_geotechnical_risk                     631773
has_geotechnical_risk_fault_crack         631773
has_geotechnical_risk_flood               631773
has_geotechnical_risk_land_settlement     631773
has_geotechnical_risk_landslide           631773
has_geotechnical_risk_liquefaction        631773
has_geotechnical_risk_other               631773
has_geotechnical_risk_rock_fall           631773
has_repair_started                        631773
vdcmun_id                                 631773
ward_id                                        0
legal_ownership_status                         0
count_families                                 0
has_secondary_use                              0
has_secondary_use_agriculture                  0
has_secondary_use_hotel                        0
has_secondary_use_rental                       0
has_secondary_use_institution                  0
has_secondary_use_school                       0
has_secondary_use_industry                     0
has_secondary_use_health_post                  0
has_secondary_use_gov_office                   0
has_secondary_use_use_police                   0
has_secondary_use_other                        0
count_floors_pre_eq                            0
count_floors_post_eq                           0
age_building                                   0
plinth_area_sq_ft                              0
height_ft_pre_eq                               0
height_ft_post_eq                              0
land_surface_condition                         0
foundation_type                                0
roof_type                                      0
ground_floor_type                              0
other_floor_type                               0
position                                       0
plan_configuration                             0
has_superstructure_adobe_mud                   0
has_superstructure_mud_mortar_stone            0
has_superstructure_stone_flag                  0
has_superstructure_cement_mortar_stone         0
has_superstructure_mud_mortar_brick            0
has_superstructure_cement_mortar_brick         0
has_superstructure_timber                      0
has_superstructure_bamboo                      0
has_superstructure_rc_non_engineered           0
has_superstructure_rc_engineered               0
has_superstructure_other                       0
condition_post_eq                              0
dtype: int64

In [102]:
merge_test2.dropna(inplace=True)

merge_test2.shape

In [103]:
merge_test2.shape

(421175, 52)

In [106]:
building1=merge_test2['building_id']

In [107]:
del merge_test2['building_id']

In [112]:
merge_test2.area_assesed = LabelEncoder().fit_transform(merge_test2.area_assesed)

In [113]:
merge_test2.head()

,area_assesed,district_id,has_geotechnical_risk,has_geotechnical_risk_fault_crack,has_geotechnical_risk_flood,has_geotechnical_risk_land_settlement,has_geotechnical_risk_landslide,has_geotechnical_risk_liquefaction,has_geotechnical_risk_other,has_geotechnical_risk_rock_fall,...,has_superstructure_stone_flag,has_superstructure_cement_mortar_stone,has_superstructure_mud_mortar_brick,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other,condition_post_eq
0,0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,1,0,0,1,2
1,0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,1,0,0,1,5
2,1,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,1,1,0,0,0,3
3,0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,0,0,0,1,1,0,0,1,2
4,1,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,0,0,0,1,1,0,0,1,3

In [114]:
pred = clf.predict(merge_test2)

In [115]:
pred[:5]

array(['Grade 4', 'Grade 5', 'Grade 5', 'Grade 3', 'Grade 5'],
      dtype=object)

In [121]:
merge_test2['damage_grade'] = pred

In [122]:
merge_test2['building_id']=building1

In [123]:
merge_test2.head()

,area_assesed,district_id,has_geotechnical_risk,has_geotechnical_risk_fault_crack,has_geotechnical_risk_flood,has_geotechnical_risk_land_settlement,has_geotechnical_risk_landslide,has_geotechnical_risk_liquefaction,has_geotechnical_risk_other,has_geotechnical_risk_rock_fall,...,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other,condition_post_eq,damag_grade,building_id,damage_grade
0,0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,1,0,0,1,2,Grade 4,a3380c4f75,Grade 4
1,0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,1,0,0,1,5,Grade 5,a338a4e653,Grade 5
2,1,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,1,0,0,0,3,Grade 5,a338a4e6b7,Grade 5
3,0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,1,0,0,1,2,Grade 3,a33a6eaa3a,Grade 3
4,1,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,1,0,0,1,3,Grade 5,a33b073ff6,Grade 5

In [124]:
submission2 = merge_test2[['building_id', 'damage_grade']]

In [125]:
submission2.shape

(421175, 2)

In [126]:
submission2.to_csv('second_sub.csv', index=False)

In [127]:
!pwd

/home/saurav/Desktop/ML Challenge